#!/bin/bash

awk -F ":" '{printf "%-25s%-10s%s\n", $1, $3, $6}' /etc/passwd

#%-25 chaine de 25 caracteres pour $1

#awk -F ":" '{print ($1, $3, $6)}' /etc/passwd | column -t
#column -t : pour aligner