#! /bin/bash

# NEED TO BE ROOT : sudo su

if [[ -f /etc/crontab_old ]]
then
    FIRST_MODIF=`md5sum --text /etc/crontab_old | awk '{print $1}'`
elif [[ -f /etc/crontab ]]
then
   FIRST_MODIF=`md5sum --text /etc/crontab | awk '{print $1}'`
fi

if [[ -f /etc/crontab ]]
then
    FILE="`md5sum --text /etc/crontab | awk '{print $1}'`"
    cp /etc/crontab /etc/crontab_old
fi

if [[ $FIRST_MODIF != $FILE ]]
then
    echo "/etc/crontab has been modified" | mail root
fi

#add crontab :
#echo '0 0 * * * root ./04' | crontab