#! /bin/bash

if [[ -f toto_old ]]
then
    FIRST_MODIF=`md5sum -q toto_old`
else
    FIRST_MODIF=`md5sum -q toto`
fi

FILE=`md5sum -q toto`
cp toto toto_old

if [[ $FIRST_MODIF == $FILE ]]
then
    echo "bitch"
fi
echo $FIRST_MODIF
echo $FILE
